# Generated by Django 4.2.29 on 2026-03-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_storeapplication'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('total_sales_inc_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hq_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pos_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wages', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opening_sales_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tab_allowance_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payable_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operating_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales_garage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hq_cash_garage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cogs_xero', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expense_xero', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_xero', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_contractor_xero', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('number_of_days', models.IntegerField(default=0)),
                ('number_of_payruns', models.IntegerField(default=0)),
                ('sales_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cogs_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wage_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('review_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_goal', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('hygiene_grade', models.CharField(default='A', max_length=5)),
                ('sales_notes', models.TextField(blank=True, default='')),
                ('cogs_notes', models.TextField(blank=True, default='')),
                ('wage_notes', models.TextField(blank=True, default='')),
                ('next_month_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sky_reports', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sky_reports', to='users.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['organization', 'year', 'month'], name='reports_sky_organiz_3caf59_idx')],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
    ]
