# Generated by Django 4.2.29 on 2026-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_profitshare_partnershare'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profitshare',
            new_name='reports_pro_organiz_beecd0_idx',
            old_name='reports_pro_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='storeevaluation',
            new_name='reports_sto_organiz_52bca6_idx',
            old_name='reports_sto_organiz_idx',
        ),
        migrations.AddField(
            model_name='profitshare',
            name='evaluation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeevaluation',
            name='period_type',
            field=models.CharField(choices=[('H1', 'H1 (Apr-Sep)'), ('H2', 'H2 (Oct-Mar)')], max_length=2),
        ),
    ]
