# Generated by Django 4.2 on 2026-03-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField()),
                ('pos_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pos_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_approved', to='users.userprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_created', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closings', to='users.organization')),
            ],
            options={
                'ordering': ['-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='ClosingSupplierCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_costs', to='closing.dailyclosing')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='closing.supplier')),
            ],
            options={
                'ordering': ['supplier__name'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyclosing',
            index=models.Index(fields=['organization', 'closing_date'], name='closing_dai_organiz_9450d0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyclosing',
            index=models.Index(fields=['status', 'closing_date'], name='closing_dai_status_57f2fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyclosing',
            unique_together={('organization', 'closing_date')},
        ),
        migrations.AddIndex(
            model_name='closingsuppliercost',
            index=models.Index(fields=['closing', 'supplier'], name='closing_clo_closing_3386b3_idx'),
        ),
    ]
