# Generated by Django 4.2 on 2026-03-06 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingHRCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='HR 현금 금액', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='HR 현금 비고', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_cash_entries_created', to=settings.AUTH_USER_MODEL)),
                ('daily_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_cash_entries', to='closing.dailyclosing')),
            ],
            options={
                'verbose_name': 'Closing HR Cash',
                'verbose_name_plural': 'Closing HR Cashes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClosingCashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SUPPLIES', '소비재'), ('MAINTENANCE', '유지보수'), ('OTHER', '기타')], help_text='지출 카테고리', max_length=20)),
                ('reason', models.CharField(help_text='지출 사유', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='지출 금액', max_digits=12)),
                ('attachment', models.FileField(blank=True, help_text='영수증 또는 증빙 파일 (PDF, JPG, PNG 최대 5MB)', null=True, upload_to='closing/expenses/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('daily_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_expenses', to='closing.dailyclosing')),
            ],
            options={
                'verbose_name': 'Closing Cash Expense',
                'verbose_name_plural': 'Closing Cash Expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='closingcashexpense',
            index=models.Index(fields=['daily_closing', 'category'], name='closing_clo_daily_c_ecc356_idx'),
        ),
    ]
