# Generated by Django 4.2.29 on 2026-03-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_ird_number_organization_logo_and_more'),
        ('closing', '0002_closinghrcash_closingcashexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_categories', to='users.organization')),
            ],
            options={
                'verbose_name_plural': 'Sales Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
