# Generated by Django 4.2.29 on 2026-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0003_salescategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='closinghrcash',
            name='photo',
            field=models.ImageField(blank=True, help_text='수령 증빙 사진', null=True, upload_to='closing/hr_cash/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='closinghrcash',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='수령인 이름', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='bank_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='은행 입금 금액', max_digits=12),
        ),
    ]
