# Generated by Django 4.2.29 on 2026-03-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_ird_number_organization_logo_and_more'),
        ('closing', '0004_add_bank_deposit_and_hr_cash_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingsuppliercost',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number from supplier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingsuppliercost',
            name='xero_invoice_id',
            field=models.CharField(blank=True, help_text='Xero invoice ID (future sync)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='closingsuppliercost',
            name='xero_status',
            field=models.CharField(blank=True, choices=[('NOT_SYNCED', 'Not Synced'), ('SYNCED', 'Synced'), ('ERROR', 'Sync Error')], default='NOT_SYNCED', help_text='Xero sync status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='xero_invoice_id',
            field=models.CharField(blank=True, help_text='Xero invoice ID (future sync)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='xero_status',
            field=models.CharField(blank=True, choices=[('NOT_SYNCED', 'Not Synced'), ('SYNCED', 'Synced'), ('ERROR', 'Sync Error')], default='NOT_SYNCED', help_text='Xero sync status', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SupplierMonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Settlement year')),
                ('month', models.IntegerField(help_text='Settlement month (1-12)')),
                ('statement_file', models.FileField(help_text='Supplier statement file (PDF, JPG, PNG, XLSX max 10MB)', upload_to='closing/supplier_statements/%Y/%m/')),
                ('statement_total', models.DecimalField(decimal_places=2, help_text='Total amount on the supplier statement', max_digits=12)),
                ('our_total', models.DecimalField(decimal_places=2, default=0, help_text='Our total from ClosingSupplierCost entries', max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, help_text='Variance = statement_total - our_total', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('MATCHED', 'Matched'), ('MISMATCHED', 'Mismatched')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('xero_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('xero_status', models.CharField(blank=True, default='NOT_SYNCED', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_statements', to='users.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='closing.supplier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'ordering': ['-year', '-month', 'supplier__name'],
                'indexes': [models.Index(fields=['organization', 'year', 'month'], name='closing_sup_organiz_8c88ea_idx'), models.Index(fields=['supplier', 'year', 'month'], name='closing_sup_supplie_17b0a4_idx')],
                'unique_together': {('organization', 'supplier', 'year', 'month')},
            },
        ),
    ]
