# Generated by Django 4.2.29 on 2026-03-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_ird_number_organization_logo_and_more'),
        ('closing', '0005_closingsuppliercost_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Close/reopen notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='months_closed', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closes', to='users.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
    ]
