# Generated by Django 4.2.29 on 2026-03-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0006_monthlyclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='tab_count',
            field=models.IntegerField(default=0, help_text='POS 탭 수 (거래 건수)'),
        ),
        migrations.CreateModel(
            name='ClosingOtherSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='매출 항목 이름 (e.g. Dining, Uber Eats)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_sales', to='closing.dailyclosing')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['closing'], name='closing_clo_closing_54eba1_idx')],
            },
        ),
    ]
