# Generated by Django 4.2.29 on 2026-03-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0008_cq_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqexpense',
            name='category',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], default='EXPENSE', max_length=10),
        ),
    ]
