# Generated by Django 4.2.29 on 2026-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0009_cq_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqexpense',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate (1 NZD = ? KRW)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cqexpense',
            name='krw_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='KRW amount received from exchange', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cqaccountbalance',
            name='account',
            field=models.CharField(choices=[('CHCH', 'ChCh'), ('QT', 'QT'), ('KRW', 'KRW')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cqexpense',
            name='account',
            field=models.CharField(choices=[('CHCH', 'ChCh'), ('QT', 'QT'), ('KRW', 'KRW')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cqexpense',
            name='category',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('EXCHANGE', 'Exchange')], default='EXPENSE', max_length=10),
        ),
    ]
