# Generated by Django 4.2.29 on 2026-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0010_cq_krw_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='variance_note',
            field=models.TextField(blank=True, help_text='Variance reason/explanation', null=True),
        ),
    ]
