# Generated by Django 4.2.29 on 2026-03-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0011_add_variance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('COGS', 'COGS'), ('MAINTENANCE', 'Maintenance'), ('GENERAL', 'General')], default='COGS', max_length=20),
        ),
    ]
