# Generated by Django 4.2.29 on 2026-03-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0012_add_supplier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingcashexpense',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='메모'),
        ),
    ]
