# Generated by Django 4.2.29 on 2026-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0013_add_cash_expense_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermonthlystatement',
            name='parsed_data',
            field=models.JSONField(blank=True, help_text='Parsed line items from Vision API: {total, line_items: [{date, description, amount}]}', null=True),
        ),
    ]
