# Generated by Django 4.2.29 on 2026-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0014_add_parsed_data_to_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ko', models.CharField(blank=True, help_text='Korean name', max_length=200)),
                ('category', models.CharField(choices=[('NZ_PUBLIC', 'NZ Public Holiday'), ('NZ_SCHOOL', 'NZ School Holiday'), ('CN_MAJOR', 'Chinese Major Holiday'), ('CN_FESTIVAL', 'Chinese Festival'), ('KR_MAJOR', 'Korean Major Holiday'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Same as start_date for single-day holidays')),
                ('year', models.IntegerField()),
                ('impact', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', help_text='Expected impact on sales', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='closing_hol_start_d_e0fe6f_idx'), models.Index(fields=['category', 'year'], name='closing_hol_categor_62aab7_idx')],
            },
        ),
    ]
