# Generated by Django 4.2.29 on 2026-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0015_add_holiday_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
