# Generated by Django 4.2.29 on 2026-03-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_annual_salary'),
        ('closing', '0016_remove_unique_supplier_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CQTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_name', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('COLLECTION', 'Collection'), ('INCENTIVE', 'Incentive'), ('PROFIT', 'Profit Distribution'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('EXCHANGE', 'Exchange')], max_length=15)),
                ('person', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('ACCOUNT', 'Account'), ('KRW', 'KRW')], default='CASH', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('period', models.CharField(blank=True, default='', help_text='반기 기간 (e.g. 2025-Oct, 2026-Apr)', max_length=20)),
                ('incentive_rate', models.DecimalField(blank=True, decimal_places=2, help_text='인센티브 비율 (0.1 = 10%)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cq_transactions_created', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cq_transactions', to='users.organization')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'date'], name='closing_cqt_organiz_14ca6c_idx'), models.Index(fields=['store_name'], name='closing_cqt_store_n_dfd48d_idx'), models.Index(fields=['person'], name='closing_cqt_person_4aea28_idx'), models.Index(fields=['transaction_type'], name='closing_cqt_transac_0a613a_idx')],
            },
        ),
    ]
