# Generated by Django 4.2.29 on 2026-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0017_cqtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='category',
            field=models.CharField(choices=[('NZ_PUBLIC', 'NZ Public Holiday'), ('NZ_REGIONAL', 'NZ Regional Anniversary'), ('NZ_SCHOOL', 'NZ School Holiday'), ('CN_MAJOR', 'Chinese Major Holiday'), ('CN_FESTIVAL', 'Chinese Festival'), ('KR_MAJOR', 'Korean Major Holiday'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
