# Generated by Django 4.2.29 on 2026-03-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0018_add_profit_share_to_cqtransaction'),
        ('closing', '0018_alter_holiday_category'),
    ]

    operations = [
    ]
