# Generated by Django 4.2.29 on 2026-03-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_hr_cash_enabled'),
        ('hr', '0004_timesheet_break_end_timesheet_break_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='shift_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='shift_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('emerald', 'Green'), ('amber', 'Amber'), ('rose', 'Rose'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('indigo', 'Indigo'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red')], default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='users.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='roster',
            name='shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosters', to='hr.shifttemplate'),
        ),
    ]
