# Generated by Django 4.2.29 on 2026-03-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_roster_shift_color_roster_shift_name_shifttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='break_minutes',
            field=models.IntegerField(default=30, help_text='Scheduled break in minutes'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='break_minutes',
            field=models.IntegerField(default=30, help_text='Break duration in minutes'),
        ),
    ]
