# Generated by Django 4.2.29 on 2026-03-09 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_job_title_alter_userprofile_work_type'),
        ('hr', '0006_add_break_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='users.organization'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks', to='hr.employeedocument'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='step_type',
            field=models.CharField(choices=[('PERSONAL_INFO', 'Personal Information'), ('BANK_ACCOUNT', 'Bank Account'), ('IR330', 'IR330 Tax Declaration'), ('DOCUMENT_SIGN', 'Document Signing'), ('FILE_UPLOAD', 'File Upload'), ('TRAINING', 'Training'), ('CUSTOM', 'Custom Task')], default='CUSTOM', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='upload_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.onboarding'),
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('SAFETY', 'Safety Training'), ('FCP', 'FCP Training'), ('HAZARD', 'Hazard Training'), ('CUSTOM', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='training_materials/%Y/%m/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='users.organization')),
            ],
            options={
                'ordering': ['sort_order', 'module_type'],
            },
        ),
        migrations.CreateModel(
            name='IR330Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ird_number', models.CharField(help_text='NZ IRD number', max_length=20)),
                ('tax_code', models.CharField(choices=[('M', 'M - Primary employment'), ('ME', 'ME - Primary + student loan'), ('SB', 'SB - Secondary < $14k'), ('S', 'S - Secondary $14k-$48k'), ('SH', 'SH - Secondary $48k-$70k'), ('ST', 'ST - Secondary $70k-$180k'), ('SA', 'SA - Secondary > $180k'), ('CAE', 'CAE - Casual agricultural'), ('EDW', 'EDW - Election day worker'), ('ND', 'ND - No declaration')], max_length=10)),
                ('is_nz_resident', models.BooleanField(default=True)),
                ('has_student_loan', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir330_declarations', to='users.userprofile')),
                ('onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ir330_declaration', to='hr.onboarding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('REGIONAL_MANAGER', 'Regional Manager'), ('HQ', 'HQ / Head Office'), ('CEO', 'CEO')], default='EMPLOYEE', max_length=20)),
                ('job_title', models.CharField(choices=[('STORE_MANAGER', 'Store Manager'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('SUPERVISOR', 'Supervisor'), ('BARISTA', 'Barista'), ('HEAD_CHEF', 'Head Chef'), ('CHEF', 'Chef'), ('COOK', 'Cook'), ('KITCHEN_HAND', 'Kitchen Hand'), ('SERVER', 'Server'), ('CASHIER', 'Cashier'), ('ALL_ROUNDER', 'All Rounder'), ('CLEANER', 'Cleaner'), ('OTHER', 'Other')], max_length=30)),
                ('work_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CASUAL', 'Casual'), ('SALARY', 'Salary'), ('VISA_FULL_TIME', 'Visa Full Time')], max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invite', to='users.userprofile')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('JOB_OFFER', 'Job Offer'), ('JOB_DESCRIPTION', 'Job Description')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='document_templates/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='users.organization')),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='related_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks', to='hr.trainingmodule'),
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['organization', 'module_type'], name='hr_training_organiz_551d66_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinvite',
            index=models.Index(fields=['organization', 'status'], name='hr_employee_organiz_3bcd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeinvite',
            index=models.Index(fields=['invite_code'], name='hr_employee_invite__93a308_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['organization', 'document_type'], name='hr_document_organiz_67128d_idx'),
        ),
    ]
