# Generated by Django 4.2.29 on 2026-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employeedocument_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='job_title',
            field=models.CharField(blank=True, choices=[('STORE_MANAGER', 'Store Manager'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('SUPERVISOR', 'Supervisor'), ('BARISTA', 'Barista'), ('HEAD_CHEF', 'Head Chef'), ('CHEF', 'Chef'), ('COOK', 'Cook'), ('KITCHEN_HAND', 'Kitchen Hand'), ('SERVER', 'Server'), ('CASHIER', 'Cashier'), ('ALL_ROUNDER', 'All Rounder'), ('CLEANER', 'Cleaner'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='work_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CASUAL', 'Casual'), ('SALARY', 'Salary'), ('VISA_FULL_TIME', 'Visa Full Time')], max_length=20, null=True),
        ),
    ]
