# Generated by Django 4.2.29 on 2026-03-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_documenttemplate_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/'),
        ),
    ]
