# Generated by Django 4.2.29 on 2026-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employeedocument_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir330declaration',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/ir330/%Y/%m/'),
        ),
    ]
