# Generated by Django 4.2.29 on 2026-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_ir330declaration_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/pdf/%Y/%m/'),
        ),
    ]
