# Generated by Django 4.2.29 on 2026-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_add_pdf_file_to_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='sign_zones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
