# Generated by Django 4.2.29 on 2026-03-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_integration_model'),
        ('hr', '0012_add_sign_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('PAY', 'Pay & Payslip'), ('SCHEDULE', 'Schedule & Roster'), ('LEAVE', 'Leave'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('reply', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='users.organization')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_inquiries', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='hr_inquiry_organiz_b04f4e_idx'), models.Index(fields=['employee'], name='hr_inquiry_employe_0750f0_idx')],
            },
        ),
    ]
