# Generated by Django 4.2.29 on 2026-03-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobtitle_remove_choices'),
        ('hr', '0014_remove_job_title_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvite',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='max_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='min_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='reporting_to',
            field=models.CharField(blank=True, default='Director/Management', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='work_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PAY', 'Pay & Payslip'), ('SCHEDULE', 'Schedule & Roster'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_last_day', models.DateField(help_text='Employee proposed last working day')),
                ('notice_period_weeks', models.IntegerField(default=2, help_text='Auto-calculated from work type')),
                ('earliest_last_day', models.DateField(help_text='Calculated: today + notice period')),
                ('confirmed_last_day', models.DateField(blank=True, help_text='Manager negotiated last day', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('manager_notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_resignations', to='users.userprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_requests', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_requests', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='hr_resignat_organiz_c88ab2_idx'), models.Index(fields=['employee'], name='hr_resignat_employe_b045d7_idx')],
            },
        ),
    ]
