# Generated by Django 4.2.29 on 2026-03-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_kpi_targets_to_organization'),
        ('hr', '0015_employeeinvite_commencement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Employment Agreement'), ('JOB_DESCRIPTION', 'Job Description'), ('JOB_OFFER', 'Job Offer'), ('VARIATION', 'Agreement Variation'), ('VISA', 'Visa / Work Permit'), ('ID_DOCUMENT', 'ID Document'), ('CERTIFICATE', 'Certificate / Licence'), ('MEDICAL', 'Medical Certificate'), ('POLICE_VET', 'Police Vetting'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='WorkplaceAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(help_text='Where in the store', max_length=255)),
                ('description', models.TextField()),
                ('injury_type', models.CharField(choices=[('MINOR', 'Minor (first aid only)'), ('MODERATE', 'Moderate (medical treatment)'), ('SERIOUS', 'Serious Harm'), ('NOTIFIABLE', 'Notifiable Event')], max_length=20)),
                ('body_part_affected', models.CharField(blank=True, default='', max_length=255)),
                ('first_aid_given', models.BooleanField(default=False)),
                ('first_aid_details', models.TextField(blank=True, default='')),
                ('medical_treatment_sought', models.BooleanField(default=False)),
                ('days_off_work', models.IntegerField(default=0)),
                ('worksafe_notified', models.BooleanField(default=False, help_text='Required for notifiable events')),
                ('worksafe_reference', models.CharField(blank=True, default='', max_length=100)),
                ('corrective_actions', models.TextField(blank=True, default='')),
                ('witness_names', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='accidents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_accidents', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_accidents', to='users.organization')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accidents', to='users.userprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'employee'], name='hr_workplac_organiz_f48483_idx'), models.Index(fields=['employee', 'date'], name='hr_workplac_employe_17e0c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('overall_rating', models.CharField(choices=[('EXCEEDS', 'Exceeds Expectations'), ('MEETS', 'Meets Expectations'), ('BELOW', 'Below Expectations'), ('UNSATISFACTORY', 'Unsatisfactory')], max_length=20)),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='', help_text='Agreed goals for next period')),
                ('employee_comments', models.TextField(blank=True, default='')),
                ('acknowledged_by_employee', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='performance_reviews/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='users.organization')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to='users.userprofile')),
            ],
            options={
                'ordering': ['-review_period_end'],
                'indexes': [models.Index(fields=['organization', 'employee'], name='hr_performa_organiz_8ac822_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MEETING', 'Meeting Notes'), ('RETURN_TO_WORK', 'Return to Work'), ('COMPLAINT', 'Complaint'), ('GRIEVANCE', 'Grievance'), ('GENERAL', 'General Note'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_confidential', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_notes/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to='users.userprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_notes', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_notes', to='users.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'employee'], name='hr_employee_organiz_63fca4_idx'), models.Index(fields=['employee', 'date'], name='hr_employee_employe_f67625_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VERBAL_WARNING', 'Verbal Warning'), ('WRITTEN_WARNING', 'Written Warning'), ('FINAL_WARNING', 'Final Warning'), ('DISCIPLINARY_MEETING', 'Disciplinary Meeting'), ('SUSPENSION', 'Suspension'), ('TERMINATION', 'Termination')], max_length=30)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='What happened, what was discussed')),
                ('outcome', models.TextField(blank=True, default='', help_text='Agreed actions, next steps')),
                ('witness', models.CharField(blank=True, default='', help_text='Support person / witness name', max_length=255)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('acknowledged_by_employee', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='disciplinary/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='users.userprofile')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_disciplinary', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='users.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'employee'], name='hr_discipli_organiz_baaac7_idx'), models.Index(fields=['employee', 'date'], name='hr_discipli_employe_150e99_idx')],
            },
        ),
    ]
