# Generated by Django 4.2 on 2026-03-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.organization')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['organization', 'date'], name='sales_sales_organiz_af068f_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['date'], name='sales_sales_date_d1cd75_idx'),
        ),
    ]
