# Generated by Django 4.2 on 2026-03-06 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_hr_cash_enabled'),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('auditor_name', models.CharField(max_length=255)),
                ('auditor_role', models.CharField(max_length=255)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('external', 'External Audit'), ('regulatory', 'Regulatory Inspection')], max_length=50)),
                ('findings', models.JSONField(default=dict, help_text='Audit findings')),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('non_compliant', 'Non-Compliant')], max_length=20, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('responses', models.JSONField(default=dict, help_text='Dictionary of item_id -> response (true/false/note)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음'), ('critical', '긴급')], max_length=20)),
                ('status', models.CharField(choices=[('reported', '보고됨'), ('investigating', '조사중'), ('resolved', '해결됨'), ('closed', '마감됨')], default='reported', max_length=20)),
                ('incident_type', models.CharField(choices=[('customer_complaint', 'Customer Complaint'), ('food_safety', 'Food Safety Issue'), ('hygiene', 'Hygiene Issue'), ('equipment', 'Equipment Issue'), ('training', 'Training Issue'), ('other', 'Other')], max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('starting', 'Starting (시작)'), ('preparing', 'Preparing (준비)'), ('cooking', 'Making & Cooking (조리)'), ('serving', 'Serving & Selling (제공 및 판매)'), ('closing', 'Closing (종료)')], max_length=20)),
                ('items', models.JSONField(default=list, help_text='Array of checklist items with description and required field')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간'), ('quarterly', '분기')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('checklist', models.JSONField(default=dict, help_text='Comprehensive FCP checklist')),
                ('responses', models.JSONField(default=dict, help_text='Verification responses')),
                ('findings', models.TextField(blank=True, help_text='Issues or concerns found', null=True)),
                ('corrective_actions', models.TextField(blank=True, help_text='Actions taken to correct issues', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='validity_months',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['expiry_date'], name='safety_trai_expiry__02a7f1_idx'),
        ),
        migrations.AddField(
            model_name='selfverificationrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_verifications', to='users.organization'),
        ),
        migrations.AddField(
            model_name='selfverificationrecord',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_verifications', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='safetychecklisttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates_created', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='safetychecklisttemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='users.organization'),
        ),
        migrations.AddField(
            model_name='incident',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='users.organization'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_resolved', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='dailychecklistresponse',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_checklists', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='dailychecklistresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checklists', to='users.organization'),
        ),
        migrations.AddField(
            model_name='dailychecklistresponse',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='safety.safetychecklisttemplate'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='selfverificationrecord',
            index=models.Index(fields=['organization', 'period_end'], name='safety_self_organiz_0bfc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='safetychecklisttemplate',
            index=models.Index(fields=['organization', 'stage', 'is_active'], name='safety_safe_organiz_627cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'status'], name='safety_inci_organiz_acc333_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'reported_at'], name='safety_inci_severit_9eba64_idx'),
        ),
        migrations.AddIndex(
            model_name='dailychecklistresponse',
            index=models.Index(fields=['organization', 'date'], name='safety_dail_organiz_e37eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailychecklistresponse',
            index=models.Index(fields=['completed_by', 'date'], name='safety_dail_complet_7ee065_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'date'], name='safety_audi_organiz_883c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['audit_type'], name='safety_audi_audit_t_99e061_idx'),
        ),
    ]
