# Generated by Django 4.2.29 on 2026-03-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_ird_number_organization_logo_and_more'),
        ('safety', '0002_auditlog_dailychecklistresponse_incident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='냉장고, 냉동고, 디스플레이 등', max_length=255)),
                ('standard_min', models.DecimalField(blank=True, decimal_places=1, help_text='기준 최저 온도 (°C)', max_digits=5, null=True)),
                ('standard_max', models.DecimalField(blank=True, decimal_places=1, help_text='기준 최고 온도 (°C)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_locations', to='users.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
