# Generated by Django 4.2.29 on 2026-03-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_ird_number_organization_logo_and_more'),
        ('safety', '0003_temperaturelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyRecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique slug: opening_checks, daily_temp, etc.', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ko', models.CharField(blank=True, help_text='Korean name for bilingual display', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('EVENT', 'Event-based'), ('SETUP', 'Setup/Reference'), ('SPECIALIST', 'Specialist')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ON_EVENT', 'On Event'), ('ONE_TIME', 'One Time')], max_length=20)),
                ('default_fields', models.JSONField(default=list, help_text='Array of field definitions: [{key, label, label_ko, type, required, options}]')),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color for UI', max_length=7)),
                ('icon', models.CharField(default='clipboard', help_text='Icon key for frontend', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=True, help_text='True = MPI-provided, False = custom')),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_model', models.CharField(blank=True, help_text='Existing model name to bridge: TemperatureRecord, CleaningRecord, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreRecordConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('assigned_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('BOTH', 'Both')], default='EMPLOYEE', max_length=10)),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Override default_fields for this store')),
                ('custom_schedule_time', models.TimeField(blank=True, help_text='Custom time for this task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_record_configs', to='users.organization')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_configs', to='safety.safetyrecordtype')),
            ],
            options={
                'ordering': ['record_type__sort_order'],
                'unique_together': {('organization', 'record_type')},
            },
        ),
        migrations.CreateModel(
            name='SafetyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Flexible field storage matching record_type.default_fields')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FLAGGED', 'Flagged'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_records_completed', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_records', to='users.organization')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='safety.safetyrecordtype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_records_reviewed', to='users.userprofile')),
            ],
            options={
                'ordering': ['-date', '-time', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'record_type', 'date'], name='safety_safe_organiz_b15b4e_idx'), models.Index(fields=['organization', 'date', 'status'], name='safety_safe_organiz_fa2e7f_idx'), models.Index(fields=['completed_by', 'date'], name='safety_safe_complet_89d515_idx'), models.Index(fields=['status', 'date'], name='safety_safe_status_e88e31_idx')],
            },
        ),
    ]
