from django.db import migrations


SYSTEM_RECORD_TYPES = [
    # ===== DAILY =====
    {
        'code': 'opening_checks',
        'name': 'Opening Checks',
        'name_ko': '오픈 체크',
        'description': 'Daily checks when opening the business',
        'category': 'DAILY',
        'frequency': 'DAILY',
        'color_code': '#10B981',
        'icon': 'sunrise',
        'sort_order': 1,
        'legacy_model': '',
        'default_fields': [
            {'key': 'staff_well', 'label': 'All working staff are well', 'label_ko': '직원 건강 상태 양호', 'type': 'checkbox', 'required': True},
            {'key': 'prep_areas_clean', 'label': 'Food preparation areas are clean', 'label_ko': '조리 구역 청결', 'type': 'checkbox', 'required': True},
            {'key': 'fridge_temps_checked', 'label': 'Fridge/chiller temperatures checked', 'label_ko': '냉장/냉동 온도 확인', 'type': 'checkbox', 'required': True},
            {'key': 'handwashing_ready', 'label': 'Handwashing facilities ready', 'label_ko': '손세정 시설 준비', 'type': 'checkbox', 'required': False},
            {'key': 'notes', 'label': 'Notes', 'label_ko': '비고', 'type': 'textarea', 'required': False},
        ],
    },
    {
        'code': 'daily_temperature',
        'name': 'Daily Temperature Checks',
        'name_ko': '일일 온도 체크',
        'description': 'Record fridge/chiller temperatures daily',
        'category': 'DAILY',
        'frequency': 'DAILY',
        'color_code': '#3B82F6',
        'icon': 'thermometer',
        'sort_order': 2,
        'legacy_model': 'TemperatureRecord',
        'default_fields': [],
    },
    {
        'code': 'daily_cleaning',
        'name': 'Daily Cleaning Tasks',
        'name_ko': '일일 청소',
        'description': 'Record daily cleaning tasks',
        'category': 'DAILY',
        'frequency': 'DAILY',
        'color_code': '#8B5CF6',
        'icon': 'spray',
        'sort_order': 3,
        'legacy_model': 'CleaningRecord',
        'default_fields': [],
    },
    {
        'code': 'closing_checks',
        'name': 'Closing Checks',
        'name_ko': '마감 체크',
        'description': 'Daily checks when closing the business',
        'category': 'DAILY',
        'frequency': 'DAILY',
        'color_code': '#F59E0B',
        'icon': 'sunset',
        'sort_order': 4,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_protected', 'label': 'Food is protected from contamination', 'label_ko': '식품 오염 방지 완료', 'type': 'checkbox', 'required': True},
            {'key': 'stored_correctly', 'label': 'Food is stored at the correct temperature', 'label_ko': '적정 온도 보관', 'type': 'checkbox', 'required': True},
            {'key': 'use_by_checked', 'label': 'Food past use-by date has been thrown away', 'label_ko': '유통기한 지난 식품 폐기', 'type': 'checkbox', 'required': True},
            {'key': 'cleaning_done', 'label': 'Cleaning has been completed', 'label_ko': '청소 완료', 'type': 'checkbox', 'required': True},
            {'key': 'rubbish_removed', 'label': 'Rubbish has been removed', 'label_ko': '쓰레기 처리 완료', 'type': 'checkbox', 'required': True},
            {'key': 'notes', 'label': 'Notes', 'label_ko': '비고', 'type': 'textarea', 'required': False},
        ],
    },
    {
        'code': 'supplier_delivery',
        'name': 'Supplier Delivery Check',
        'name_ko': '입고 검수',
        'description': 'Check deliveries from trusted suppliers',
        'category': 'DAILY',
        'frequency': 'DAILY',
        'color_code': '#06B6D4',
        'icon': 'truck',
        'sort_order': 5,
        'legacy_model': '',
        'default_fields': [
            {'key': 'supplier_name', 'label': 'Supplier name', 'label_ko': '공급사명', 'type': 'text', 'required': True},
            {'key': 'food_type', 'label': 'Type of food', 'label_ko': '식품 종류', 'type': 'text', 'required': True},
            {'key': 'batch_lot', 'label': 'Batch/Lot number', 'label_ko': '배치/로트 번호', 'type': 'text', 'required': False},
            {'key': 'quantity', 'label': 'Quantity', 'label_ko': '수량', 'type': 'text', 'required': True},
            {'key': 'temperature', 'label': 'Temperature °C (if applicable)', 'label_ko': '온도 °C', 'type': 'number', 'required': False},
            {'key': 'condition_ok', 'label': 'Condition acceptable', 'label_ko': '상태 양호', 'type': 'checkbox', 'required': True},
            {'key': 'notes', 'label': 'Notes', 'label_ko': '비고', 'type': 'textarea', 'required': False},
        ],
    },
    # ===== WEEKLY =====
    {
        'code': 'equipment_maintenance',
        'name': 'Equipment & Facilities Maintenance',
        'name_ko': '장비 점검',
        'description': 'Maintenance checks and repairs for equipment and facilities',
        'category': 'WEEKLY',
        'frequency': 'WEEKLY',
        'color_code': '#64748B',
        'icon': 'wrench',
        'sort_order': 10,
        'legacy_model': '',
        'default_fields': [
            {'key': 'equipment_name', 'label': 'Equipment/item', 'label_ko': '장비/항목', 'type': 'text', 'required': True},
            {'key': 'check_type', 'label': 'Check type', 'label_ko': '점검 유형', 'type': 'select', 'required': True, 'options': ['Routine check', 'Repair', 'Replacement', 'Calibration']},
            {'key': 'condition', 'label': 'Condition', 'label_ko': '상태', 'type': 'select', 'required': True, 'options': ['Good', 'Needs attention', 'Requires repair']},
            {'key': 'action_taken', 'label': 'What was done', 'label_ko': '조치 사항', 'type': 'textarea', 'required': False},
            {'key': 'next_check_date', 'label': 'Next check date', 'label_ko': '다음 점검일', 'type': 'date', 'required': False},
        ],
    },
    # ===== MONTHLY =====
    {
        'code': 'thermometer_calibration',
        'name': 'Thermometer Checks / Calibration',
        'name_ko': '온도계 검교정',
        'description': 'Check and calibrate thermometers for accuracy',
        'category': 'MONTHLY',
        'frequency': 'MONTHLY',
        'color_code': '#EC4899',
        'icon': 'calibrate',
        'sort_order': 11,
        'legacy_model': '',
        'default_fields': [
            {'key': 'thermometer_id', 'label': 'Thermometer ID', 'label_ko': '온도계 번호', 'type': 'text', 'required': True},
            {'key': 'ice_reading', 'label': 'Temperature °C in iced water', 'label_ko': '얼음물 측정값 °C', 'type': 'number', 'required': True},
            {'key': 'boiling_reading', 'label': 'Temperature °C in boiling water', 'label_ko': '끓는물 측정값 °C', 'type': 'number', 'required': False},
            {'key': 'accurate', 'label': 'Thermometer is accurate', 'label_ko': '온도계 정확', 'type': 'checkbox', 'required': True},
            {'key': 'action_taken', 'label': 'Action if inaccurate', 'label_ko': '부정확 시 조치', 'type': 'textarea', 'required': False},
        ],
    },
    {
        'code': 'internal_audit',
        'name': 'Internal Audit / Verification',
        'name_ko': '자체 점검',
        'description': 'Regular internal audits to verify your food safety plan',
        'category': 'MONTHLY',
        'frequency': 'MONTHLY',
        'color_code': '#D97706',
        'icon': 'search',
        'sort_order': 12,
        'legacy_model': 'SelfVerificationRecord',
        'default_fields': [],
    },
    # ===== EVENT-BASED =====
    {
        'code': 'something_wrong',
        'name': 'When Something Goes Wrong',
        'name_ko': '사고 보고',
        'description': 'Record when something goes wrong and what was done to fix it',
        'category': 'EVENT',
        'frequency': 'ON_EVENT',
        'color_code': '#EF4444',
        'icon': 'alert',
        'sort_order': 20,
        'legacy_model': '',
        'default_fields': [
            {'key': 'what_went_wrong', 'label': 'What went wrong?', 'label_ko': '무엇이 잘못됐는가?', 'type': 'textarea', 'required': True},
            {'key': 'staff_involved', 'label': 'Staff involved', 'label_ko': '관련 직원', 'type': 'text', 'required': False},
            {'key': 'fix_action', 'label': 'What did you do to fix it?', 'label_ko': '어떻게 해결했는가?', 'type': 'textarea', 'required': True},
            {'key': 'prevent_action', 'label': 'What did you do to stop it happening again?', 'label_ko': '재발 방지 조치', 'type': 'textarea', 'required': True},
            {'key': 'food_safe', 'label': 'How did you keep food safe?', 'label_ko': '식품 안전 확보 방법', 'type': 'textarea', 'required': True},
        ],
    },
    {
        'code': 'customer_complaint',
        'name': 'Customer Complaints',
        'name_ko': '고객 불만',
        'description': 'Record customer complaints and resolution',
        'category': 'EVENT',
        'frequency': 'ON_EVENT',
        'color_code': '#F97316',
        'icon': 'user-x',
        'sort_order': 21,
        'legacy_model': '',
        'default_fields': [
            {'key': 'customer_name', 'label': 'Customer name and contact', 'label_ko': '고객명 및 연락처', 'type': 'text', 'required': False},
            {'key': 'purchase_date', 'label': 'Date and time of purchase', 'label_ko': '구매 일시', 'type': 'text', 'required': False},
            {'key': 'affected_food', 'label': 'Affected food (batch/lot)', 'label_ko': '관련 식품', 'type': 'text', 'required': False},
            {'key': 'complaint', 'label': 'Complaint details', 'label_ko': '불만 내용', 'type': 'textarea', 'required': True},
            {'key': 'cause', 'label': 'Cause of the problem', 'label_ko': '원인', 'type': 'textarea', 'required': True},
            {'key': 'action_taken', 'label': 'Action taken', 'label_ko': '조치 내용', 'type': 'textarea', 'required': True},
            {'key': 'resolved_by', 'label': 'Managed/resolved by', 'label_ko': '처리자', 'type': 'text', 'required': False},
        ],
    },
    {
        'code': 'staff_sickness',
        'name': 'Staff Sickness',
        'name_ko': '직원 병가',
        'description': 'Record staff sickness and return to work',
        'category': 'EVENT',
        'frequency': 'ON_EVENT',
        'color_code': '#A855F7',
        'icon': 'heart',
        'sort_order': 22,
        'legacy_model': '',
        'default_fields': [
            {'key': 'staff_name', 'label': 'Staff name', 'label_ko': '직원명', 'type': 'text', 'required': True},
            {'key': 'symptoms', 'label': 'Symptoms', 'label_ko': '증상', 'type': 'textarea', 'required': False},
            {'key': 'date_sick', 'label': 'Date became sick', 'label_ko': '발병일', 'type': 'date', 'required': True},
            {'key': 'date_returned', 'label': 'Date returned to work', 'label_ko': '복귀일', 'type': 'date', 'required': False},
            {'key': 'action_taken', 'label': 'Action taken', 'label_ko': '조치 사항', 'type': 'textarea', 'required': False},
        ],
    },
    # ===== SETUP/REFERENCE =====
    {
        'code': 'allergen_info',
        'name': 'Allergens in Your Food',
        'name_ko': '알레르기 정보',
        'description': 'Record allergen information for your food items',
        'category': 'SETUP',
        'frequency': 'ONE_TIME',
        'color_code': '#14B8A6',
        'icon': 'alert-triangle',
        'sort_order': 30,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_dish', 'label': 'Food/dish', 'label_ko': '식품/메뉴', 'type': 'text', 'required': True},
            {'key': 'ingredients', 'label': 'Ingredients', 'label_ko': '재료', 'type': 'textarea', 'required': True},
            {'key': 'allergens', 'label': 'Allergens', 'label_ko': '알레르겐', 'type': 'text', 'required': True},
        ],
    },
    {
        'code': 'traceability',
        'name': 'Traceability',
        'name_ko': '식품 추적성',
        'description': 'Record traceability information for food items',
        'category': 'SETUP',
        'frequency': 'ONE_TIME',
        'color_code': '#6366F1',
        'icon': 'link',
        'sort_order': 31,
        'legacy_model': '',
        'default_fields': [
            {'key': 'supplier', 'label': 'Supplier name and contact', 'label_ko': '공급사 정보', 'type': 'text', 'required': True},
            {'key': 'manufacturer', 'label': 'Manufacturer name and contact', 'label_ko': '제조사 정보', 'type': 'text', 'required': False},
            {'key': 'product_type', 'label': 'Product type', 'label_ko': '제품 종류', 'type': 'text', 'required': True},
            {'key': 'brand', 'label': 'Brand', 'label_ko': '브랜드', 'type': 'text', 'required': False},
            {'key': 'best_before', 'label': 'Best before / use by', 'label_ko': '유통기한', 'type': 'date', 'required': False},
            {'key': 'batch_lot', 'label': 'Batch/Lot information', 'label_ko': '배치/로트 정보', 'type': 'text', 'required': False},
        ],
    },
    # ===== SPECIALIST =====
    {
        'code': 'sushi_rice_acidifying',
        'name': 'Acidifying Rice (Sushi)',
        'name_ko': '초밥 식초 처리',
        'description': 'Proving acidifying method and batch checks for sushi rice',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#EAB308',
        'icon': 'rice',
        'sort_order': 40,
        'legacy_model': '',
        'default_fields': [
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'ph_reading', 'label': 'pH of rice', 'label_ko': 'pH 수치', 'type': 'number', 'required': True},
            {'key': 'is_batch_check', 'label': 'Is this a batch check?', 'label_ko': '배치 체크 여부', 'type': 'checkbox', 'required': False},
        ],
    },
    {
        'code': 'cooling_sushi_rice',
        'name': 'Cooling Acidified Sushi Rice',
        'name_ko': '초밥 밥 냉각',
        'description': 'Cooling times and temperatures for acidified sushi rice',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#EAB308',
        'icon': 'rice',
        'sort_order': 41,
        'legacy_model': '',
        'default_fields': [
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'start_temp', 'label': 'Start temp °C', 'label_ko': '시작 온도', 'type': 'number', 'required': True},
            {'key': 'second_temp', 'label': '2nd check temp °C', 'label_ko': '2차 체크 온도', 'type': 'number', 'required': False},
            {'key': 'third_temp', 'label': '3rd check temp °C', 'label_ko': '3차 체크 온도', 'type': 'number', 'required': False},
        ],
    },
    {
        'code': 'chinese_roast_duck',
        'name': 'Drying Chinese Style Roast Duck',
        'name_ko': '중식 오리구이 건조',
        'description': 'Method proving and batch checks for Chinese style roast duck',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#0D9488',
        'icon': 'drumstick',
        'sort_order': 42,
        'legacy_model': '',
        'default_fields': [
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'temp_start', 'label': 'Start temp °C', 'label_ko': '시작 온도', 'type': 'number', 'required': True},
            {'key': 'temp_halfway', 'label': 'Halfway temp °C', 'label_ko': '중간 온도', 'type': 'number', 'required': False},
            {'key': 'time_finished', 'label': 'Time drying finished', 'label_ko': '건조 완료 시간', 'type': 'time', 'required': True},
        ],
    },
    {
        'code': 'doner_kebabs',
        'name': 'Making Doner Kebabs',
        'name_ko': '도너 케밥 제조',
        'description': 'Batch checks for doner kebabs',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#0D9488',
        'icon': 'kebab',
        'sort_order': 43,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_type', 'label': 'Food type', 'label_ko': '식품 종류', 'type': 'text', 'required': True},
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'temp_cooked_to', 'label': 'Temp °C food is cooked to', 'label_ko': '조리 온도', 'type': 'number', 'required': True},
        ],
    },
    {
        'code': 'sous_vide',
        'name': 'Sous Vide',
        'name_ko': '수비드 조리',
        'description': 'Method proving and batch checks for sous vide cooking',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#0D9488',
        'icon': 'sous-vide',
        'sort_order': 44,
        'legacy_model': '',
        'default_fields': [
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'water_bath_temp', 'label': 'Water bath temp °C', 'label_ko': '수조 온도', 'type': 'number', 'required': True},
            {'key': 'internal_temp_start', 'label': 'Internal temp °C at start', 'label_ko': '시작 내부 온도', 'type': 'number', 'required': True},
            {'key': 'holding_time', 'label': 'Length of holding time', 'label_ko': '유지 시간', 'type': 'text', 'required': True},
            {'key': 'internal_temp_end', 'label': 'Internal temp °C at end', 'label_ko': '종료 내부 온도', 'type': 'number', 'required': True},
        ],
    },
    {
        'code': 'hot_smoking',
        'name': 'Hot Smoking',
        'name_ko': '훈연 조리',
        'description': 'Method proving and batch checks for hot smoking food',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#BE185D',
        'icon': 'flame',
        'sort_order': 45,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food', 'label': 'Food', 'label_ko': '식품', 'type': 'text', 'required': True},
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'smoke_house_temp', 'label': 'Smoke house temp °C', 'label_ko': '훈연실 온도', 'type': 'number', 'required': True},
            {'key': 'core_temp', 'label': 'Core temp °C at end', 'label_ko': '종료 코어 온도', 'type': 'number', 'required': True},
        ],
    },
    {
        'code': 'biltong',
        'name': 'Biltong Making',
        'name_ko': '빌통 제조',
        'description': 'Recording each batch of biltong',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#78716C',
        'icon': 'meat',
        'sort_order': 46,
        'legacy_model': '',
        'default_fields': [
            {'key': 'product', 'label': 'Product', 'label_ko': '제품', 'type': 'text', 'required': True},
            {'key': 'batch_id', 'label': 'Batch ID', 'label_ko': '배치 ID', 'type': 'text', 'required': True},
            {'key': 'meat_type', 'label': 'Meat type', 'label_ko': '고기 종류', 'type': 'text', 'required': True},
            {'key': 'dryer_temp', 'label': 'Dryer temperature °C', 'label_ko': '건조기 온도', 'type': 'number', 'required': False},
            {'key': 'weight_loss_pct', 'label': '% weight loss', 'label_ko': '중량 감소율 %', 'type': 'number', 'required': False},
        ],
    },
    {
        'code': 'cooking_poultry',
        'name': 'Cooking Poultry, Mince & Liver',
        'name_ko': '가금류/다진고기/간 조리',
        'description': 'Method proving and batch checks for cooking poultry, mince and liver',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#BE185D',
        'icon': 'chicken',
        'sort_order': 47,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_dish', 'label': 'Food/dish', 'label_ko': '식품/요리', 'type': 'text', 'required': True},
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'internal_temp', 'label': 'Internal temp °C (thickest part)', 'label_ko': '내부 온도', 'type': 'number', 'required': True},
        ],
    },
    {
        'code': 'reheating',
        'name': 'Reheating Food',
        'name_ko': '재가열',
        'description': 'Method proving and batch checks for reheating food',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#BE185D',
        'icon': 'reheat',
        'sort_order': 48,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_dish', 'label': 'Food/dish', 'label_ko': '식품/요리', 'type': 'text', 'required': True},
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'internal_temp', 'label': 'Internal temp °C', 'label_ko': '내부 온도', 'type': 'number', 'required': True},
        ],
    },
    {
        'code': 'cooling_food',
        'name': 'Cooling Freshly Cooked Food',
        'name_ko': '조리 식품 냉각',
        'description': 'Cooling method and batch checks for freshly cooked food',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#BE185D',
        'icon': 'snowflake',
        'sort_order': 49,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_dish', 'label': 'Food/dish', 'label_ko': '식품/요리', 'type': 'text', 'required': True},
            {'key': 'batch', 'label': 'Batch #', 'label_ko': '배치 번호', 'type': 'text', 'required': True},
            {'key': 'start_temp', 'label': 'Start temp °C', 'label_ko': '시작 온도', 'type': 'number', 'required': True},
            {'key': 'second_temp', 'label': '2nd check temp °C', 'label_ko': '2차 온도', 'type': 'number', 'required': False},
            {'key': 'third_temp', 'label': '3rd check temp °C', 'label_ko': '3차 온도', 'type': 'number', 'required': False},
        ],
    },
    {
        'code': 'transported_food',
        'name': 'Transported Food Temperature',
        'name_ko': '운송 식품 온도',
        'description': 'Temperature checks for transported food',
        'category': 'SPECIALIST',
        'frequency': 'DAILY',
        'color_code': '#F97316',
        'icon': 'truck-temp',
        'sort_order': 50,
        'legacy_model': '',
        'default_fields': [
            {'key': 'food_dish', 'label': 'Food/dish', 'label_ko': '식품', 'type': 'text', 'required': True},
            {'key': 'temperature', 'label': 'Temperature °C', 'label_ko': '온도 °C', 'type': 'number', 'required': True},
            {'key': 'time_out', 'label': 'Time out of temperature control', 'label_ko': '온도 관리 이탈 시간', 'type': 'text', 'required': False},
        ],
    },
]


def seed_record_types(apps, schema_editor):
    SafetyRecordType = apps.get_model('safety', 'SafetyRecordType')
    for rt_data in SYSTEM_RECORD_TYPES:
        SafetyRecordType.objects.update_or_create(
            code=rt_data['code'],
            defaults=rt_data,
        )


def reverse_seed(apps, schema_editor):
    SafetyRecordType = apps.get_model('safety', 'SafetyRecordType')
    codes = [rt['code'] for rt in SYSTEM_RECORD_TYPES]
    SafetyRecordType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_safetyrecordtype_storerecordconfig_safetyrecord'),
    ]

    operations = [
        migrations.RunPython(seed_record_types, reverse_seed),
    ]
