# Generated by Django 4.2.29 on 2026-03-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_managed_stores'),
        ('safety', '0005_seed_mpi_record_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_areas', to='users.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
