# Generated by Django 4.2 on 2026-03-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_periods', to='users.organization')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('organization', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kiwisaver', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acc_levy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_slips', to='payroll.payperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_slips', to='users.userprofile')),
            ],
            options={
                'ordering': ['-pay_period__start_date'],
                'unique_together': {('pay_period', 'user')},
            },
        ),
    ]
