# Generated by Django 4.2.29 on 2026-03-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_hr_cash_enabled'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in NZD', max_digits=8)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime rate multiplier (1.5x = 150%)', max_digits=4)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='payperiod',
            name='period_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_acc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslip',
            name='kiwisaver_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payslip',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payslip',
            name='regular_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='payperiod',
            index=models.Index(fields=['organization', 'is_finalized'], name='payroll_pay_organiz_e9cbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['user', 'pay_period'], name='payroll_pay_user_id_af0cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['is_locked'], name='payroll_pay_is_lock_8b4d04_idx'),
        ),
        migrations.AddField(
            model_name='salary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='users.organization'),
        ),
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['user', 'is_active'], name='payroll_sal_user_id_2695cb_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['organization', 'is_active'], name='payroll_sal_organiz_09ae69_idx'),
        ),
    ]
