# Generated by Django 4.2.29 on 2026-03-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_job_title_alter_userprofile_work_type'),
        ('payroll', '0002_salary_payperiod_period_type_payslip_employer_acc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('FAMILY_VIOLENCE', 'Family Violence Leave'), ('ALTERNATIVE', 'Alternative Holiday')], max_length=20)),
                ('balance_hours', models.DecimalField(decimal_places=2, default=0, help_text='Current available hours', max_digits=8)),
                ('accrued_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total accrued since last reset', max_digits=8)),
                ('used_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total used since last reset', max_digits=8)),
                ('entitlement_date', models.DateField(blank=True, help_text='Date when leave entitlement begins (6 months after start)', null=True)),
                ('last_anniversary', models.DateField(blank=True, help_text='Last annual leave anniversary date', null=True)),
                ('year', models.IntegerField(help_text='Year for this balance record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user', 'leave_type'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('FAMILY_VIOLENCE', 'Family Violence Leave'), ('ALTERNATIVE', 'Alternative Holiday')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total leave hours requested', max_digits=8)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid (max of OWP, AWE)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayDayFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FILED', 'Filed')], default='PENDING', max_length=20)),
                ('file_data', models.JSONField(blank=True, help_text='IRD employment information data', null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(help_text='Filing deadline (payment_date + 2 business days)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Actual date')),
                ('observed_date', models.DateField(help_text='Observed date (after Mondayisation)')),
                ('name', models.CharField(max_length=100)),
                ('is_national', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, choices=[('AUCKLAND', 'Auckland'), ('WELLINGTON', 'Wellington'), ('CANTERBURY', 'Canterbury'), ('OTAGO', 'Otago'), ('WAIKATO', 'Waikato'), ('BAY_OF_PLENTY', 'Bay of Plenty'), ('HAWKES_BAY', "Hawke's Bay"), ('TARANAKI', 'Taranaki'), ('MANAWATU_WHANGANUI', 'Manawatū-Whanganui'), ('NELSON', 'Nelson'), ('MARLBOROUGH', 'Marlborough'), ('WEST_COAST', 'West Coast'), ('SOUTHLAND', 'Southland'), ('NORTHLAND', 'Northland'), ('GISBORNE', 'Gisborne'), ('CHATHAM_ISLANDS', 'Chatham Islands')], help_text='Region for anniversary days (null = national)', max_length=30, null=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['observed_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payperiod',
            name='payroll_pay_organiz_e9cbbe_idx',
        ),
        migrations.AddField(
            model_name='payperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='alternative_holidays_earned',
            field=models.IntegerField(default=0, help_text='Alternative holidays (lieu days) earned this period'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='esct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ESCT on employer KiwiSaver', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='holiday_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='8% for CASUAL employees', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='public_holiday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours worked on public holidays', max_digits=8),
        ),
        migrations.AddField(
            model_name='payslip',
            name='public_holiday_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Time & half extra (0.5x portion)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='student_loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_code',
            field=models.CharField(blank=True, default='M', help_text='Tax code at time of generation', max_length=10),
        ),
        migrations.AddIndex(
            model_name='payperiod',
            index=models.Index(fields=['organization', 'status'], name='payroll_pay_organiz_e06bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['year', 'observed_date'], name='payroll_pub_year_668cc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('date', 'region', 'year')},
        ),
        migrations.AddField(
            model_name='paydayfiling',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payday_filings', to='users.organization'),
        ),
        migrations.AddField(
            model_name='paydayfiling',
            name='pay_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payday_filings', to='payroll.payperiod'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='users.organization'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.organization'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='paydayfiling',
            index=models.Index(fields=['organization', 'status'], name='payroll_pay_organiz_b4f660_idx'),
        ),
        migrations.AddIndex(
            model_name='paydayfiling',
            index=models.Index(fields=['due_date'], name='payroll_pay_due_dat_b2c89d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'status'], name='payroll_lea_user_id_1861f7_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', 'status'], name='payroll_lea_organiz_487d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_lea_start_d_f88429_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['user', 'leave_type', 'year'], name='payroll_lea_user_id_d3b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['organization', 'leave_type'], name='payroll_lea_organiz_ec65c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'leave_type', 'year')},
        ),
    ]
