# Generated by Django 4.2.29 on 2026-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_leavebalance_leaverequest_paydayfiling_publicholiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Supporting document (e.g. medical certificate)', null=True, upload_to='leave_attachments/'),
        ),
    ]
