# Generated by Django 4.2.29 on 2026-03-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_leaverequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
