# Generated by Django 4.2 on 2026-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hr_cash_enabled',
            field=models.BooleanField(default=True, help_text='HR 현금 입력 활성화 여부'),
        ),
    ]
