# Generated by Django 4.2.29 on 2026-03-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_hr_cash_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ird_number',
            field=models.CharField(blank=True, help_text='IRD 번호', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='otherwise_working_threshold',
            field=models.PositiveIntegerField(default=7, help_text='그 중 몇 번 근무해야 적용'),
        ),
        migrations.AddField(
            model_name='organization',
            name='otherwise_working_weeks',
            field=models.PositiveIntegerField(default=8, help_text='몇 주 기간 확인'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, choices=[('AUCKLAND', 'Auckland'), ('WELLINGTON', 'Wellington'), ('CANTERBURY', 'Canterbury'), ('OTAGO', 'Otago'), ('WAIKATO', 'Waikato'), ('BAY_OF_PLENTY', 'Bay of Plenty'), ('HAWKES_BAY', "Hawke's Bay"), ('TARANAKI', 'Taranaki'), ('MANAWATU_WHANGANUI', 'Manawatū-Whanganui'), ('NELSON', 'Nelson'), ('MARLBOROUGH', 'Marlborough'), ('WEST_COAST', 'West Coast'), ('SOUTHLAND', 'Southland'), ('NORTHLAND', 'Northland'), ('GISBORNE', 'Gisborne'), ('CHATHAM_ISLANDS', 'Chatham Islands')], help_text='NZ 지역 (Anniversary Day 적용)', max_length=30, null=True),
        ),
    ]
