# Generated by Django 4.2.29 on 2026-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_job_title_alter_userprofile_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, help_text='NZ bank account number', max_length=30, null=True),
        ),
    ]
