# Generated by Django 4.2.29 on 2026-03-10 21:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_integration_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enabled_modules',
            field=models.JSONField(default=users.models.get_default_modules, help_text='활성화된 모듈 목록'),
        ),
    ]
