# Generated by Django 4.2.29 on 2026-03-10 21:40

from django.db import migrations

DEFAULT_MODULES = [
    'CLOSING', 'CASHUP', 'REPORTS', 'SALES', 'ROSTER',
    'TIMESHEET', 'HR', 'PAYROLL', 'TASKS', 'SAFETY',
    'DOCUMENTS', 'INQUIRIES',
]


def populate_modules(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    for org in Organization.objects.all():
        if not org.enabled_modules:
            org.enabled_modules = list(DEFAULT_MODULES)
            org.save(update_fields=['enabled_modules'])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_enabled_modules'),
    ]

    operations = [
        migrations.RunPython(populate_modules, reverse_populate),
    ]
