# Generated by Django 4.2.29 on 2026-03-10 22:57

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_populate_enabled_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, default='', max_length=20)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.TextField(blank=True, default='')),
                ('store_phone', models.CharField(blank=True, default='', max_length=20)),
                ('desired_modules', models.JSONField(default=users.models.get_default_modules)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
