# Generated by Django 4.2.29 on 2026-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_storeapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_stores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 'STORE'}, related_name='managers', to='users.organization'),
        ),
    ]
