# Generated by Django 4.2.29 on 2026-03-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobtitle_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_daily_close',
            field=models.BooleanField(default=False, help_text='Daily Close 수행 권한'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_safety_tasks',
            field=models.BooleanField(default=False, help_text='Safety Tasks 수행 권한'),
        ),
    ]
