# Generated by Django 4.2.29 on 2026-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_can_daily_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='food_cost_target',
            field=models.DecimalField(decimal_places=2, default=32.0, help_text='식재료비 목표 %', max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='labour_cost_target',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='인건비율 목표 %', max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_revenue_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='월 매출 목표', max_digits=12, null=True),
        ),
    ]
