# Generated by Django 4.2.29 on 2026-03-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_kpi_targets_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='housing_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Housing support 주당 금액 (NZD)', max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='housing_support',
            field=models.BooleanField(default=False, help_text='Housing support 활성화'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transport_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport allowance 주당 금액 (NZD)', max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transport_support',
            field=models.BooleanField(default=False, help_text='Transport allowance 활성화'),
        ),
    ]
