# Generated by Django 4.2.29 on 2026-03-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annual_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='연봉 (NZD) - Salary Full Time 전용', max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CASUAL', 'Casual'), ('SALARY', 'Salary'), ('SALARY_FULLTIME', 'Salary Full Time'), ('VISA_FULL_TIME', 'Visa Full Time')], default='FULL_TIME', max_length=20),
        ),
    ]
